apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: api
  labels:
    app: api
spec: {}
status: {}

---
  
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: web
  labels:
    app: web
spec: {}
status: {}