apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "KVOH4"
    objects: |
      array:
        - |
          objectName: SQL-USER              
          objectType: secret
          objectAlias: "SQL_USER"
          objectVersion: ""
        - |
          objectName: SQL-PASSWORD              
          objectType: secret
          objectAlias: "SQL_PASSWORD"
          objectVersion: ""
        - |
          objectName: SQL-SERVER              
          objectType: secret
          objectAlias: "SQL_SERVER"
          objectVersion: ""
        - |
          objectName: SQL-DBNAME              
          objectType: secret
          objectAlias: "SQL_DBNAME"
          objectVersion: ""
    tenantId: "58b7c60b-390f-463b-9c11-bed265b95451"